development:
  adapter: postgresql
  encoding: utf8
  database: df3rmb3qtccqkc
  pool: 5
  timeout: 5000
  username: uhbmzujseznrem
  password: OuWG5mmfbxGWOylIrRPAePDSGe
  port: 5432
  host: ec2-54-228-213-113.eu-west-1.compute.amazonaws.com

test:
  adapter: postgresql
  encoding: utf8
  database: test
  pool: 5
  timeout: 5000
  username: root
  password: S3cur1ty
  port: 5432
  host: localhost
  
production:
  adapter: postgresql
  encoding: utf8
  database: df3rmb3qtccqkc
  pool: 5
  timeout: 5000
  username: uhbmzujseznrem
  password: OuWG5mmfbxGWOylIrRPAePDSGe
  port: 5432
  host: ec2-54-228-213-113.eu-west-1.compute.amazonaws.com
