development:
  adapter: postgresql
  encoding: utf8
  database: development
  host: localhost
  pool: 5
  timeout: 5000
  username: root
  password: S3cur1ty
  port: 5432
  host: localhost

test:
  adapter: postgresql
  encoding: utf8
  database: test
  pool: 5
  timeout: 5000
  username: root
  password: S3cur1ty
  port: 5432
  host: localhost
  
production:
  adapter: postgresql
  encoding: utf8
  database: production
  pool: 5
  timeout: 5000
  username: root
  password: S3cur1ty
  port: 5432
  host: localhost
